version: '3.9'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
    ports:
      - "3306:3306"

  backend:
    build: .
    restart: always
    depends_on:
      - mysql
  
  reverse-proxy:
    build: ./reverse-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend

  