import Typography from "@mui/material/Typography";
import Button from "@mui/material/Button";
import Card from "@mui/material/Card";
import Dialog from "@mui/material/Dialog";
import DialogActions from "@mui/material/DialogActions";
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useMutation } from "react-query";
import axios from "axios";

// Generated by https://quicktype.io

export interface PostParticipantBody {
  competition_id: number;
  user_id: number;
  status: string;
  role: string;
}

const postParticipant = (body: PostParticipantBody) => {
  return axios.post("/api/participant", body);
};

interface Props {
  competition: any;
  uid: number;
}

export const Competition = ({ competition, uid }: Props) => {
  return (
    <Card sx={{ mb: 2 }}>
      <Typography variant="h6" component="div" sx={{ p: 2 }}>
        {competition.title}
      </Typography>
      <Typography variant="body1" component="div" sx={{ p: 2 }}>
        {competition.sub_title}
      </Typography>

      <Button
        onClick={() => (window.location.href = `/scoring/${competition.id}`)}
        sx={{ ml: 2, mb: 2 }}
        variant="contained"
      >
        查看記分板
      </Button>
    </Card>
  );
};
