// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "NYCU archery",
            "url": "https://github.com/NYCUarchery",
            "email": "???"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/competition": {
            "get": {
                "description": "get id, name, date, hostID, scoreboardURL, and overview only",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "competition"
                ],
                "summary": "get information of all the competitions",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/response.AllCompInfoResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "create a competition and set the person as the host",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "competition"
                ],
                "summary": "create a competition",
                "parameters": [
                    {
                        "type": "string",
                        "description": "competition name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "date",
                        "name": "date",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "a list of groups",
                        "name": "groups",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "overview",
                        "name": "overview",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Scoreboard URL",
                        "name": "scoreboardURL",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/response.CompResponse"
                        }
                    },
                    "400": {
                        "description": "competition name exists | cannot parse date string | invalid info/groups",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "DB error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/competition/{id}": {
            "get": {
                "description": "get info, groups, participants of the competition",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "competition"
                ],
                "summary": "get information of the competition",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "competition id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/response.CompInfoResponse"
                        }
                    },
                    "400": {
                        "description": "empty/invalid competition id",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "no competition found",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/participant/": {
            "post": {
                "description": "add a particpant to the competition",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "participant"
                ],
                "summary": "join in a competition",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "competition id",
                        "name": "competitionID",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "no user/competition found",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/session": {
            "post": {
                "description": "get a session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "login",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user's name",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "password",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success | has loginned",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "wrong username or password",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete the session",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "logout",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/user": {
            "post": {
                "description": "add a user to db",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "register a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user's name",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "password",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "email",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "overview",
                        "name": "overview",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "institution ID",
                        "name": "institutionID",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "username/email exists | empty username/password/email | invalid info",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "db error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/user/me": {
            "get": {
                "description": "get my uid in the session",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "get my uid",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/response.UIDResponse"
                        }
                    }
                }
            }
        },
        "/user/{id}": {
            "get": {
                "description": "get a user's username, overview, and institution id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "get a user's information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user's id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/response.UserInfoResponse"
                        }
                    },
                    "400": {
                        "description": "empty/invalid user id",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "404": {
                        "description": "no user found",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "modify username, password, overview, and institution_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "modify user's information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user's id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "original password",
                        "name": "oriPassword",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "modified password",
                        "name": "modPassword",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "modified email",
                        "name": "email",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "modified overview",
                        "name": "overview",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "modified institution ID",
                        "name": "institutionID",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "400": {
                        "description": "empty/invalid user id | invalid modified information",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "403": {
                        "description": "cannot change other's info | wrong original password",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "response.AllCompInfoResponse": {
            "type": "object",
            "properties": {
                "competitions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.Competition"
                    }
                },
                "result": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "response.CompInfoResponse": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string",
                    "example": "2006-01-02T15:04:05+08:00"
                },
                "groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.Group"
                    }
                },
                "hostID": {
                    "type": "string",
                    "example": "87"
                },
                "name": {
                    "type": "string",
                    "example": "competition name"
                },
                "overview": {
                    "type": "string",
                    "example": "overview"
                },
                "participants": {
                    "type": "string",
                    "example": "[1, 2, 3, 87]"
                },
                "result": {
                    "type": "string",
                    "example": "success"
                },
                "scoreboardURL": {
                    "type": "string",
                    "example": "Scoreboard URL"
                }
            }
        },
        "response.CompResponse": {
            "type": "object",
            "properties": {
                "compID": {
                    "type": "integer",
                    "example": 87
                },
                "result": {
                    "type": "string",
                    "example": "result description"
                }
            }
        },
        "response.Competition": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string",
                    "example": "2006-01-02T15:04:05+08:00"
                },
                "hostID": {
                    "type": "string",
                    "example": "87"
                },
                "name": {
                    "type": "string",
                    "example": "competition name"
                },
                "overview": {
                    "type": "string",
                    "example": "overview"
                },
                "scoreboardURL": {
                    "type": "string",
                    "example": "Scoreboard URL"
                }
            }
        },
        "response.Group": {
            "type": "object",
            "properties": {
                "bowType": {
                    "type": "string",
                    "example": "bow type"
                },
                "competition_id": {
                    "type": "integer",
                    "example": 87
                },
                "gameRange": {
                    "type": "integer",
                    "example": 50
                },
                "groupName": {
                    "type": "string",
                    "example": "group name"
                },
                "id": {
                    "type": "integer",
                    "example": 87
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "result": {
                    "type": "string",
                    "example": "result description"
                }
            }
        },
        "response.UIDResponse": {
            "type": "object",
            "properties": {
                "uid": {
                    "type": "string",
                    "example": "your uid"
                }
            }
        },
        "response.UserInfoResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user email"
                },
                "institutionID": {
                    "type": "string",
                    "example": "user institution id"
                },
                "name": {
                    "type": "string",
                    "example": "user name"
                },
                "overview": {
                    "type": "string",
                    "example": "user overview"
                },
                "result": {
                    "type": "string",
                    "example": "success"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/",
	Schemes:          []string{},
	Title:            "Archery backend API",
	Description:      "A gin server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
