import Typography from "@mui/material/Typography";
import Button from "@mui/material/Button";
import Card from "@mui/material/Card";
import Dialog from "@mui/material/Dialog";
import DialogActions from "@mui/material/DialogActions";
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useMutation } from "react-query";
import axios from "axios";

// Generated by https://quicktype.io

export interface PostParticipantBody {
  competition_id: number;
  user_id: number;
  status: string;
  role: string;
}

const postParticipant = (body: PostParticipantBody) => {
  return axios.post("/api/participant", body);
};

interface Props {
  competition: any;
  uid: number;
}

export const Competition = ({ competition, uid }: Props) => {
  const [open, setOpen] = useState(false);
  const navigate = useNavigate();
  const { mutate: apply } = useMutation(postParticipant);

  const handleJoin = () => {
    setOpen(true);
  };

  const handlePlayeApplication = () => {
    apply({
      competition_id: competition.id,
      user_id: uid,
      status: "pending",
      role: "player",
    });
    setOpen(false);
  };

  const handleAdminApplication = () => {
    apply({
      competition_id: competition.id,
      user_id: uid,
      status: "pending",
      role: "admin",
    });
    setOpen(false);
  };

  return (
    <Card sx={{ mb: 2 }}>
      <Typography variant="h6" component="div" sx={{ p: 2 }}>
        {competition.title}
      </Typography>
      <Typography variant="body1" component="div" sx={{ p: 2 }}>
        {competition.subtitle}
      </Typography>

      <Button onClick={() => navigate(`scoring/${competition.id}`)}></Button>
      <Button onClick={handleJoin}></Button>
      <Dialog open={open} onClose={() => setOpen(false)}>
        <DialogActions>
          <Button onClick={handleAdminApplication}>申請為管理員</Button>
          <Button onClick={handlePlayeApplication}>申請為選手</Button>
        </DialogActions>
      </Dialog>
    </Card>
  );
};
